name: "Github Profile Repositories"
description: "Automatically create repositories list for your Github Profile"
branding:
  icon: "check-circle"
  color: "red"
inputs:
  github-token:
    description: "The Github token."
    required: true
  template-file:
    description: "The file template to render."
    required: true
  render-file:
    description: "The rendered out put file."
    default: 'README.md'
    required: false
  repositories:
    description: "Allow to list your repositories"
    default: true
    required: false
  repositories-limit:
    description: "The limit number of repositories will render"
    default: 10
    required: false
  repositories-order-by:
    description: "The method to sort the repositories list. Support (STARGAZERS|CREATED_AT|UPDATED_AT|PUSHED_AT|NAME). By default, it will using `STARGAZERS`."
    default: 'STARGAZERS'
    required: false
  contributed-repositories:
    description: "Allow to list contributed repositories"
    default: true
    required: false
  contributed-limit:
    description: "The limit number of contributed repositories will render"
    default: 10
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
